### ISSUE TITLE
Can't modify attribute in Document node

### ISSUE THREAD

**Issue by misterti** [shenghai/xmodifier#1]
I had to change XModifier.java createAttributeByXPath() method to below, to be able to change attribute, because node of type Document could not be cast to Element. It was causing a cast exception
java.lang.ClassCastException: com.sun.org.apache.xerces.internal.dom.DeferredDocumentImpl cannot be cast to org.w3c.dom.Element

Corrected method:
    private void createAttributeByXPath(Node node, String current, String value) {
      if (node instanceof Document)
        ((Element)((Document)node).getDocumentElement()).setAttribute(current, value);
      else
        ((Element) node).setAttribute(current, value);
    }

**Comment by shenghai** [comment]
Hi, misterti
   Thanks for trying the code : )
   The createAttributeByXPath may no need to change, but the exception (ClassCastException) is very confuse, I will update it to make it more clear.
   The reason why exception here is about trying to add attribute to Document, but it's impossible, Document is top node, and it is invisible in XML, I think you are trying to add a attribute to "document element", which is the child node of "document" node.  

for example xml:
```
<root xmlns="http://localhost">
    <element1></element1>
    <element2></element2>
    <element3></element3>
</root>
```

to add an attribute to document element, the xpath like below:
`/ns:root/@value = 100`

which will get the expected result:
```
<root xmlns="http://localhost" value=100>
    <element1></element1>
    <element2></element2>
    <element3></element3>
</root>
```

but if the xpath is like
`/@value = 100`
this will cause class cast exception, the xpath is trying to modify document node ( the xpath is "/" ), which is impossible.

----
Buy the way,  java doc of org.w3c.dom.Document: 
```
    /**
     * This is a convenience attribute that allows direct access to the child
     * node that is the document element of the document.
     */
    public Element getDocumentElement();
```

**Comment by misterti** [comment]
You are right, 
if i add root element tag name (/root/@value) instead of only attribute name /@value to xpath expression, than it works fine.
Thanks.
It's a fine library you made :)
